// Using official-looking assets from the Deadlock Wiki
const IMG_BASE = "https://deadlock.wiki/images";

export const DEADLOCK_CHARACTERS = [
  { name: "Abrams", color: "#4a5568", image: `${IMG_BASE}/3/3a/Abrams_card.png` },
  { name: "Bebop", color: "#e53e3e", image: `${IMG_BASE}/b/b3/Bebop_card.png` },
  { name: "Dynamo", color: "#3182ce", image: `${IMG_BASE}/7/7c/Dynamo_card.png` },
  { name: "Grey Talon", color: "#38a169", image: `${IMG_BASE}/a/ab/Grey_Talon_card.png` },
  { name: "Haze", color: "#805ad5", image: `${IMG_BASE}/4/4d/Haze_card.png` },
  { name: "Infernus", color: "#dd6b20", image: `${IMG_BASE}/0/00/Infernus_card.png` },
  { name: "Ivy", color: "#38a169", image: `${IMG_BASE}/5/56/Ivy_card.png` },
  { name: "Kelvin", color: "#63b3ed", image: `${IMG_BASE}/f/fc/Kelvin_card.png` },
  { name: "Lady Geist", color: "#e53e3e", image: `${IMG_BASE}/d/d7/Lady_Geist_card.png` },
  { name: "Lash", color: "#4a5568", image: `${IMG_BASE}/2/27/Lash_card.png` },
  { name: "McGinnis", color: "#d69e2e", image: `${IMG_BASE}/5/5c/McGinnis_card.png` },
  { name: "Mo & Krill", color: "#744210", image: `${IMG_BASE}/e/e1/Mo_%26_Krill_card.png` },
  { name: "Paradox", color: "#319795", image: `${IMG_BASE}/e/e3/Paradox_card.png` },
  { name: "Pocket", color: "#5a67d8", image: `${IMG_BASE}/d/df/Pocket_card.png` },
  { name: "Seven", color: "#3182ce", image: `${IMG_BASE}/3/33/Seven_card.png` },
  { name: "Shiv", color: "#9b2c2c", image: `${IMG_BASE}/5/59/Shiv_card.png` },
  { name: "Vindicta", color: "#4a5568", image: `${IMG_BASE}/f/f7/Vindicta_card.png` },
  { name: "Warden", color: "#2c5282", image: `${IMG_BASE}/3/3c/Warden_card.png` },
  { name: "Wraith", color: "#4a5568", image: `${IMG_BASE}/7/7c/Wraith_card.png` },
  { name: "Yamato", color: "#9b2c2c", image: `${IMG_BASE}/2/2b/Yamato_card.png` },
  { name: "Viscous", color: "#38a169", image: `${IMG_BASE}/c/cc/Viscous_card.png` },
  { name: "Mirage", color: "#d69e2e", image: `${IMG_BASE}/0/00/Mirage_card.png` },
  // Hero Labs / Unreleased Heroes
  { name: "Vyper", color: "#319795", image: `${IMG_BASE}/a/a9/Vyper_card.png` },
  { name: "Holliday", color: "#d69e2e", image: `${IMG_BASE}/0/0e/Holliday_card.png` },
  { name: "Rem", color: "#805ad5", image: `${IMG_BASE}/a/a8/Rem_card.png` },
  { name: "Graves", color: "#4a5568", image: `${IMG_BASE}/1/16/Graves_card.png` },
  { name: "Silver", color: "#63b3ed", image: `${IMG_BASE}/9/99/Silver_card.png` },
  { name: "Venator", color: "#e53e3e", image: `${IMG_BASE}/c/c4/Venator_card.png` },
  { name: "Celeste", color: "#5a67d8", image: `${IMG_BASE}/3/3c/Celeste_card.png` },
  { name: "Apollo", color: "#dd6b20", image: `${IMG_BASE}/5/51/Apollo_card.png` },
  { name: "Mina", color: "#805ad5", image: `${IMG_BASE}/d/d3/Mina_card.png` },
  { name: "Billy", color: "#d69e2e", image: `${IMG_BASE}/6/60/Billy_card.png` },
  { name: "Drifter", color: "#4a5568", image: `${IMG_BASE}/f/f4/Drifter_card.png` },
  { name: "Paige", color: "#38a169", image: `${IMG_BASE}/1/12/Paige_card.png` },
  { name: "The Doorman", color: "#2c5282", image: `${IMG_BASE}/f/fd/Doorman_card.png` },
  { name: "Victor", color: "#e53e3e", image: `${IMG_BASE}/f/fb/Victor_card.png` },
  { name: "Calico", color: "#4a5568", image: `${IMG_BASE}/0/0f/Calico_card.png` },
  { name: "Sinclair", color: "#d69e2e", image: `${IMG_BASE}/2/22/Sinclair_card.png` }
];
